
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/hb
  redis:
    host: 127.0.0.1





hb:
  user:
    defaultNickName: 用户昵称
  security:
    whiteList: /user/login, /user/register, /user/register/mobile
