
spring:
  profiles:
    active: @profiles.active@ # 切换环境
  mvc:
    throw-exception-if-no-handler-found: true # 404异常抛异常需开启
  web:
    resources:
      add-mappings: false # 404异常抛异常需关闭

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出
    map-underscore-to-camel-case: true # 开启驼峰


server:
  port: 1026 #端口

# JWT配置
jwt:
  enable: true
  token-header: "Bearer " # 令牌头
  secret: aaaxxx # 秘钥
  expiration: 1 # 认证令牌过期时间(小时)
  refresh-expiration: 24 # 刷新令牌过期时间(小时)
