
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/hb
  redis:
    host: 127.0.0.1


# 阿里云oss配置
aliyun:
  enable-oss: true
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  access-key-secret: 1290490343-05-4
  access-key-id: djskj43054545

