spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://124.220.180.141/hb
  redis:
    host: 124.220.180.141


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出
    map-underscore-to-camel-case: true # 开启驼峰


server:
  port: 1026 #端口

# JWT配置
jwt:
  config:
    token-header: Authorization # 请求头中的名字
    secret: JWTSecret # 秘钥
    expiration: 86400 # 过期时间


