
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1/hb
  redis:
    host: 127.0.0.1


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台输出
    map-underscore-to-camel-case: true # 开启驼峰


server:
  port: 1026 #端口

# JWT配置
jwt:
  token-header: "Bearer " # 令牌头
  secret: aaaxxx # 秘钥
  expiration: 1 # 认证令牌过期时间(小时)
  refresh-expiration: 24 # 刷新令牌过期时间(小时)
